### ISSUE TITLE
How do I use it? And does it work on V1.19.62

### ISSUE THREAD

**Issue by randomMurgi** [ddf8196/MaterialBinLoader#2]
I have no idea about experimenting with these. How do I complete the 3rd step?

**Comment by ENDERMANYK** [comment]
no it doesn't support 1.19.62 but you can find pre-made apk by me in yss Discord, for the third part you need an application called patchelf and executed it in commandline

**Comment by Onlyacat233** [comment]
to use it, U can download the pathelf from https://github.com/NixOS/patchelf . and follow the readme. U also can download the patched version from https://github.com/DominoKorean/Render-dragon-shader-list/blob/main/patchedapp.md
(I'm not good at Engilish)
